# Generated by Django 5.0.6 on 2026-04-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feusers', '0003_feuser_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owning_feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feusers.feuser')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owning_feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feusers.feuser')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledExpense',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('default_settled', models.BooleanField(default=True)),
                ('repeat_base_date', models.DateField(blank=True, null=True)),
                ('repeat_every_factor', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_every_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_expenses', to='budget.category')),
                ('owning_feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feusers.feuser')),
                ('tags', models.ManyToManyField(blank=True, related_name='scheduled_expenses', to='budget.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_due', models.DateField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('settled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.category')),
                ('owning_feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feusers.feuser')),
                ('tags', models.ManyToManyField(blank=True, related_name='expenses', to='budget.tag')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
