# Generated by Django 5.0.6 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
