# Generated by Django 5.0.6 on 2026-04-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expense_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_scheduled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='budget.scheduledexpense'),
        ),
    ]
