# Generated by Django 5.0.6 on 2026-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expense_source_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexpense',
            name='payee',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
