# Generated by Django 5.0.6 on 2026-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_scheduledexpense_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal')], max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduledexpense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal')], max_length=12),
        ),
    ]
