# Generated by Django 5.0.6 on 2026-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_add_savings_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='auto_settle_on_due_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledexpense',
            name='default_auto_settle_on_due_date',
            field=models.BooleanField(default=False),
        ),
    ]
