# Generated by Django 5.0.6 on 2026-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_expense_buddy_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcard',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='is_buddies_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notify',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal'), ('carry_over', 'Carry-Over')], max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduledexpense',
            name='notify',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='scheduledexpense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal'), ('carry_over', 'Carry-Over')], max_length=12),
        ),
    ]
