# Generated by Django 5.0.6 on 2026-06-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_expensedataoverlay_note'),
        ('feusers', '0022_feuser_backdrop_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedataoverlay',
            name='feuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_data_overlays', to='feusers.feuser'),
        ),
    ]
