# Generated by Django 5.0.6 on 2026-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_expensedataoverlay_feuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedataoverlay',
            name='note',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
