# Generated by Django 5.0.6 on 2026-06-08 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_expensedataoverlay_note_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expensedataoverlay',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduledexpense',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
