# Generated by Django 5.0.6 on 2026-06-22 13:33

from django.db import migrations, models


def drop_carry_over_expenses(apps, schema_editor):
    Expense = apps.get_model('budget', 'Expense')
    Expense.objects.filter(type='carry_over').delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_cleanup_empty_dashboards'),
    ]

    operations = [
        migrations.RunPython(drop_carry_over_expenses, noop),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal')], max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduledexpense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_dep', 'Savings Deposit'), ('savings_wit', 'Savings Withdrawal')], max_length=12),
        ),
    ]
