# Generated by Django 5.0.6 on 2026-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_clear_invalid_buddy_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='scheduled_occurrence_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scheduledexpense',
            name='last_run',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
