# Generated by Django 5.0.6 on 2026-07-16 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_backfill_scheduled_integrity_fields'),
        ('feusers', '0039_yubikeyfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_mod', models.DateTimeField(default=django.utils.timezone.now)),
                ('feuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sankey_graph', to='feusers.feuser')),
            ],
        ),
    ]
