from decimal import Decimal

from django.db.models import Sum

from .date_utils import current_financial_month, financial_month_range
from .expense_factory import create_expense
from .models import Expense, TransactionType


def _prev_financial_month(year: int, month: int) -> tuple[int, int]:
    if month == 1:
        return year - 1, 12
    return year, month - 1


def _compute_left(feuser, start, end) -> Decimal:
    qs = Expense.objects.filter(
        owning_feuser=feuser,
        date_due__gte=start,
        date_due__lte=end,
    )

    def _sum(q):
        return q.aggregate(t=Sum("value"))["t"] or Decimal("0")

    income      = _sum(qs.filter(type="income"))
    carry_over  = _sum(qs.filter(type="carry_over"))
    paid        = _sum(qs.filter(type="expense", settled=True))
    outstanding = _sum(qs.filter(type="expense", settled=False))
    sav_dep     = _sum(qs.filter(type="savings_dep"))
    sav_wit     = _sum(qs.filter(type="savings_wit"))
    savings     = sav_dep - sav_wit
    return income + carry_over - paid - outstanding - savings


def run_transition_for_user(feuser) -> str | None:
    """
    Check if a new financial month has started for `feuser` and, if so,
    apply the configured unspent-allowance action.

    Returns a short description of what was done, or None if nothing was needed.
    """
    cur_year, cur_month = current_financial_month(feuser.month_start_day, feuser.month_start_prev)
    current_key = f"{cur_year}-{cur_month}"

    if feuser.allowance_transition_month == current_key:
        return None

    action = feuser.unspent_allowance_action
    if action == "do_nothing":
        feuser.allowance_transition_month = current_key
        feuser.save(update_fields=["allowance_transition_month"])
        return None

    prev_year, prev_month = _prev_financial_month(cur_year, cur_month)
    prev_start, prev_end = financial_month_range(
        prev_year, prev_month, feuser.month_start_day, feuser.month_start_prev
    )
    left = _compute_left(feuser, prev_start, prev_end)

    feuser.allowance_transition_month = current_key
    feuser.save(update_fields=["allowance_transition_month"])

    if left <= Decimal("0"):
        return None

    cur_start, _ = financial_month_range(
        cur_year, cur_month, feuser.month_start_day, feuser.month_start_prev
    )

    if action == "deposit_savings":
        create_expense(
            owning_feuser=feuser,
            title=f"Unspent allowance ({prev_year}-{prev_month:02d})",
            type=TransactionType.SAVINGS_DEPOSIT,
            value=left,
            note="Auto-generated by month transition",
            date_due=prev_end,
            settled=True,
        )
        return f"savings_deposit {left}"

    if action == "carry_over":
        create_expense(
            owning_feuser=feuser,
            title=f"Carry-over from {prev_year}-{prev_month:02d}",
            type=TransactionType.CARRY_OVER,
            value=left,
            note="Auto-generated by month transition",
            date_due=cur_start,
            settled=True,
        )
        return f"carry_over {left}"

    return None
