# Generated by Django 5.0.6 on 2026-06-04 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0009_buddygroup_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyspending',
            name='approval_state',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
