# Generated by Django 5.0.6 on 2026-06-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0010_buddyspending_approval_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyspending',
            name='consent_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
