# Generated by Django 5.0.6 on 2026-06-08 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0011_buddyspending_consent_set_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyinvite',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buddylink',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buddyonboardinginvite',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buddyspending',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dummymergeinvite',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dummyuser',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
