# Generated by Django 5.0.6 on 2026-06-11 07:59

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0012_buddyinvite_last_mod_buddylink_last_mod_and_more'),
        ('feusers', '0026_feuser_notify_own_partnership_changes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPartnership',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPartnershipInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=None, null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_invites_sent', to='feusers.feuser')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='buddies.catalogpartnership')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPartnershipMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('feuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_membership', to='feusers.feuser')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='buddies.catalogpartnership')),
            ],
            options={
                'unique_together': {('partnership', 'feuser')},
            },
        ),
    ]
