# Generated by Django 5.0.6 on 2026-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0013_catalogpartnership_catalogpartnershipinvite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogpartnershipinvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='catalogpartnershipinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_setup', 'In Setup'), ('active', 'Active'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
    ]
