# Generated by Django 5.0.6 on 2026-06-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0014_replace_accepted_with_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyonboardinginvite',
            name='dummy',
        ),
    ]
