# Generated by Django 5.0.6 on 2026-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='confirmation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feuser',
            name='password',
            field=models.CharField(default='!', max_length=255),
        ),
    ]
