# Generated by Django 5.0.6 on 2026-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0002_feuser_confirmation_token_feuser_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuser',
            name='password_reset_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
