# Generated by Django 5.0.6 on 2026-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0003_feuser_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feuser',
            name='currency',
            field=models.CharField(blank=True, default='€', max_length=10),
        ),
    ]
