# Generated by Django 5.0.6 on 2026-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0004_feuser_anthropic_api_key_feuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='email_change_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
