# Generated by Django 5.0.6 on 2026-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0010_feuser_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
