# Generated by Django 5.0.6 on 2026-06-08 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0024_feuser_split_expense_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
