# Generated by Django 5.0.6 on 2026-06-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0025_feuser_last_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='notify_own_partnership_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feuser',
            name='notify_someones_partnership_changes',
            field=models.BooleanField(default=True),
        ),
    ]
