# Generated by Django 5.0.6 on 2026-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0026_feuser_notify_own_partnership_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feuser',
            name='special_ai_trial_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
