# Generated by Django 5.0.6 on 2026-06-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0014_replace_accepted_with_status'),
        ('budget', '0024_scheduledexpense_assignment_fields'),
        ('feusers', '0027_feuser_is_demo_and_special_ai_trial_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense_reminders', 'Expense due date reminders'), ('expense_settled', 'Expense marked as paid'), ('expense_participation', 'Shared expense participation'), ('expense_assignments', 'Expense assignment'), ('participant_decisions', 'Participant decisions'), ('settlements', 'Settlements'), ('group_activity', 'Project membership'), ('own_partnership_changes', 'Partnership changes (you)'), ('someones_partnership_changes', 'Partnership changes (others)')], max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('owning_feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='feusers.feuser')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='budget.expense')),
                ('related_feuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feusers.feuser')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buddies.project')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
