# Generated by Django 5.0.6 on 2026-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0028_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='intro_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuser',
            name='last_upgrade_intro_v_seen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
