# Generated by Django 5.0.6 on 2026-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0029_feuser_intro_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='app_v_created_at',
            field=models.CharField(default='2.0.7', max_length=20),
        ),
    ]
