# Generated by Django 5.0.6 on 2026-06-22 13:33

from django.db import migrations, models


def reassign_carry_over_users(apps, schema_editor):
    FeUser = apps.get_model('feusers', 'FeUser')
    FeUser.objects.filter(unspent_allowance_action='carry_over').update(
        unspent_allowance_action='deposit_savings'
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0031_feuser_disable_ai_ui'),
    ]

    operations = [
        migrations.RunPython(reassign_carry_over_users, noop),
        migrations.AlterField(
            model_name='feuser',
            name='unspent_allowance_action',
            field=models.CharField(choices=[('do_nothing', 'be dropped'), ('deposit_savings', 'be deposited as savings')], default='do_nothing', max_length=20),
        ),
    ]
