# Generated by Django 5.0.6 on 2026-07-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0037_remove_totp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.CharField(max_length=64)),
                ('feuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feusers.feuser')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
