# Generated by Django 5.0.6 on 2026-07-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feusers', '0039_yubikeyfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuser',
            name='enable_early_access',
            field=models.BooleanField(default=False),
        ),
    ]
